# Generated by Django 3.1.3 on 2020-11-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('quantity_g', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('energy_kcal', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('image_url', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('expiration_date', models.DateField()),
                ('fridge_id', models.CharField(max_length=50, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
