# Generated by Django 3.1.3 on 2020-12-04 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('quantity_g', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('energy_kcal', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('image_url', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('expiration_date', models.DateField()),
                ('fridge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fridge')),
            ],
        ),
    ]
