# Generated by Django 3.1.3 on 2020-12-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201205_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fridge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.fridge'),
        ),
    ]
