# Generated by Django 3.1.3 on 2020-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201115_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fridge_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
